export { default as About } from './About'
export { default as BaseLayout } from '../components/layout/BaseLayout'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'
export { default as Error } from './Error'
export { default as Home } from './Home'
export { default as Store } from './Store'
